language: python
python:
  - "3.6"
  - "3.5"
  - "3.7-dev"
install:
  - python -m pip install -r requirements.txt
  - python -m pip install -r requirements-dev.txt
script:
  - PYTHONPATH=$PWD pytest
  - ./utils/run_coverage.py
  - ./utils/run_pylint.py
branches:
  only:
  - master
